const val kotlinVersion = "1.5.30"
const val jvmTargetVersion = "16"

const val libVersion = "0.3.0-SNAPSHOT"

const val springBootVersion = "2.5.4"
const val dependencyManagementVersion = "1.0.11.RELEASE"
const val coroutinesVersion = "1.5.1"
const val serializationVersion = "1.2.2"

const val immutaleJsVersion = "3.8.2"
const val dexxVersion = "0.7"
const val logbackVersion = "1.2.5"
const val coreJsVersion = "3.16.3"
const val reactVersion = "17.0.2"
const val inlineStylePrefixerVersion = "6.0.0"
const val styledComponentsVersion = "5.3.1"
const val kotlinxHtmlVersion = "0.7.3"

const val wrapperKotlinVersion = "pre.236-kotlin-1.5.30"
const val kotlinReactVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinReactDomVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinStyledVersion = "5.3.0-$wrapperKotlinVersion"
const val kotlinExtensionsVersion = "1.0.1-$wrapperKotlinVersion"
const val kotlinCssVersion = "1.0.0-$wrapperKotlinVersion"
