const val kotlinVersion = "1.6.10"
const val jvmTargetVersion = "17"
const val javaVersion = 17
const val jvmToolchainVersion = 17
const val libVersion = "0.4.0-SNAPSHOT"

const val springBootVersion = "2.6.3"
const val dependencyManagementVersion = "1.0.11.RELEASE"
const val coroutinesVersion = "1.6.0"
const val serializationVersion = "1.3.1"

const val immutaleJsVersion = "4.0.0"
const val dexxVersion = "0.7"
const val logbackVersion = "1.2.11"
//const val coreJsVersion = "3.16.3"
const val reactVersion = "17.0.2"
const val inlineStylePrefixerVersion = "6.0.1"
const val styledComponentsVersion = "5.3.3"
//const val kotlinxHtmlVersion = "0.7.3"

const val muiMaterialVersion = "5.5.0"
const val muiIconsVersion = "5.5.0"
const val muiStylesVersion = "5.5.0"
const val emotionStyledVersion = "11.8.1"
const val emotionReactVersion = "11.8.2"
//const val materialUiCoreVersion = "4.12.3"
//const val materialUiIconsVersion = "4.11.2"
//const val materialUiLabVersion = "4.0.0-alpha.60"

const val wrapperKotlinVersion = "pre.320-kotlin-1.6.10"
//const val wrapperKotlinVersion = "pre.236-kotlin-1.5.30"
const val kotlinReactVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinReactDomVersion = "17.0.2-$wrapperKotlinVersion"
const val kotlinStyledVersion = "5.3.3-$wrapperKotlinVersion"
const val kotlinExtensionsVersion = "1.0.1-$wrapperKotlinVersion"
const val kotlinCssVersion = "1.0.0-$wrapperKotlinVersion"
